### PR TITLE
semver patches only

### PR DESCRIPTION
**Pull request by bcomnes**
This makes it so we only get semver patches.

### CODE REVIEW

**Comment by ungoldman** [comment]
Is this really needed?

**Comment by bcomnes** [comment]
I'm not totally sure.  Should we look into what kinds of changes a major range will bring in over time?

**Comment by ungoldman** [comment]
`^` is for minor, not major, and shouldn't break anything as long as dependencies are following semver. eslint-config-standard and others use `^` too

**Comment by bcomnes** [comment]
The issue was new rules that weren't there getting added, which come in on minor patches.  I'm indifferent about what to do here.  

Maybe we do this until we clean up the rest of the project, then go mack to minor updates?

**Comment by ungoldman** [comment]
ok i get it now

**Comment by dlmanning** [comment]
yeah, semver has slightly different implications when it comes to linting rules

**Pull request merged**
